##############################################################################
#   This section is for information about the station.

[Station]
    
....
    
    # Set to type of station hardware. There must be a corresponding stanza
    # in this file, which includes a value for the 'driver' option.
    station_type = WeatherFlowUDP
    
....

##############################################################################
#
[WeatherFlowUDP]
    driver = user.weatherflowudp
    log_raw_packets = False
    udp_address = 127.0.0.1
    udp_port = 4002
    udp_timeout = 180
    share_socket = true
    
    [[sensor_map]]
        outTemp = air_temperature.A8610A000101.obs_air
        outHumidity = relative_humidity.A8610A000101.obs_air
        pressure = station_pressure.A8610A000101.obs_air
        windSpeed = wind_speed.A8610A000101.rapid_wind
        windDir = wind_direction.A8610A000101.rapid_wind
